extends:
  - recommended

rules:
  security-defined: off
  no-empty-servers: off
  operation-summary: off
  operation-operationId: off
  operation-4xx-response: warn
  info-license: off
  tag-description: off
